### ISSUE TITLE
Error during install process 

### ISSUE THREAD

**Issue by DocMinus** [ASKCOS/askcos-deploy#2]
Running the 
bash deploy.sh deploy -f docker-compose.yml
I get near the end of the script the following error:
....
Pulling rabit (rabbitmq:3.8-alpine)...
ERROR: Get "https://registry-1.docker.io/v2/library/rabbitmq/manifest/sha256:...key...": dial tcp: lookup registry-1.docker.io: No address associated with hostname

I admit I am sort of running blind here with the whole installation process. I installed the askcos-base (which made and installed the docker images). but I am not clear about what I have to do in addition to that (start the images manually?). Running a testscript complains that askcos cannot be imported (of course, more of an issue for the other repo). Hoping that this deploy for the GUI would take care of all that. but now I am stuck it seems. And contrary to the readme, there is no additional info on askcos.github.io.
Any suggestions or further guidance would be appreciated. Thanks.

**Comment by mliu49** [comment]
Hello @DocMinus! Did you check out the [release info page](https://askcos.github.io/#/2021-01/?id=quickstart-using-google-cloud) on askcos.github.io? The exact procedure will differ depending on exactly what you're looking to do. If you want to deploy the web application using the pre-built Docker images on Docker Hub, then all you need is this repo (askcos-deploy) and the deploy.sh script for starting everything up. If you want to import modules into custom Python scripts, then you likely want to clone askcos-core and askcos-data directly, without containerizing with Docker.

Can you confirm whether Docker works as expected on your system? (e.g. `docker pull rabbitmq:3.8-alpine`) The error suggests DNS or firewall issues with accessing Docker Hub.

**Comment by DocMinus** [comment]
@mliu49 thanks for quick reply.
I didn't realize there were more details under the specific releases.
Running the test script for base/core was just to check if all was ok. 
Main purpose is to get the web-gui up and running (for now).

Yes, docker pull rabbit.... works without error. 
attempted again to run the script, but stops at same point. Will try a google instance install instead/alt. ask a colleague if he can decipher the dockerlogs / journalctl entries in the meantime. probably firewall related as you write. do you know which standard ports are used? maybe I can open them up.

**Comment by mliu49** [comment]
It's difficult to tell what the problem is if you're able to pull images directly using docker cli but not with docker-compose. I assume docker engine uses standard https ports for pulling images, but I'm not sure.

It's also odd since if you did successfully pull the rabbitmq image manually, then docker-compose should have found the local copy and moved on to the next step.

ASKCOS itself listens on 80 and 443 by default (via the nginx service). Communication between different services in the deployment happens on a number of ports, but that all happens on the private network set up by docker-compose.

**Comment by DocMinus** [comment]
So, I run this on a different machine and it works. (took me a while to figure out that the server is on 127.0.0.1 ... or, even simpler, localhost ...)
Don't know why I on the other machine I get above mentioned error. I removed even docker and reinstalled but the same happens. But I guess, for now, we can conclude it's some local security setting that is messing things up, not the installer per se.
Thus I guess we can close this issue.
